"""followers

Revision ID: 12328ebc320f
Revises: a83b18b0aedd
Create Date: 2018-03-05 12:26:40.055914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12328ebc320f'
down_revision = 'a83b18b0aedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
